// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"
)

// Injectors from wire.go:

func InitializeServer(logger *slog.Logger) *Server {
	repositoryA := NewRepositoryA(logger)
	serviceA := NewServiceA(repositoryA, logger)
	repositoryB := NewRepositoryB(logger)
	serviceB := NewServiceB(repositoryB, logger)
	server := &Server{
		ServiceA: serviceA,
		ServiceB: serviceB,
		logger:   logger,
	}
	return server
}
