// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
}

type AddUserResponse struct {
	Message string `json:"message"`
}

type DeleteUserRequest struct {
	Username string `json:"username" path:"username"`
}

type DeleteUserResponse struct {
	Message string `json:"message"`
}

type GetUserRequest struct {
	Username string `form:"username"`
	Email    string `form:"email"`
	Phone    string `form:"phone"`
	Page     int    `form:"page"`
	PerPage  int    `form:"per_page"`
}

type GetUserResponse struct {
	Message string     `json:"message"`
	Page    int        `json:"page"`
	PerPage int        `json:"per_page"`
	Total   int        `json:"total"`
	Data    []UserData `json:"data"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message string `json:"message"`
	Token   string `json:"token"`
}

type UpdateUserRequest struct {
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
}

type UpdateUserResponse struct {
	Message string `json:"message"`
}

type UserData struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
}
