// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeEvent 注入器: 声明需要的返回类型, Wire 会生成依赖注入代码
// phrase 作为参数传入, 会传递给 NewMessage
func InitializeEvent(phrase string) Event {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}
